---
- hosts: DEMO
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: create list of users
      action: user name='{{item}}' state=present
      with_items:
        - xyz
        - abc
        - 123
